---
- name: Download Kibana
  get_url:
    url: "{{ kibana_url }}"
    dest: "/tmp/kibana-{{ kibana_version }}.tar.gz"
    mode: 0755
    timeout: 60
    validate_certs: false
  register: get_kibana
  until: get_kibana is succeeded
  tags: kibana
- name: Create directory for Kibana
  become: true
  file:
    state: directory
    path: "{{ kibana_home }}"
  tags: kibana
- name: Extract Kibana archive
  become: true
  unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}.tar.gz"
    dest: "{{ kibana_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin"
  tags:
    - skip_ansible_lint
    - kibana
- name: Export env for Kibana
  become: true
  template:
    src: kibana.sh.j2
    dest: /etc/profile.d/kibana.sh
  tags: kibana