---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check Kibana installation
    shell:
      cmd: "/opt/kibana/7.12.1/bin/kibana --version --allow-root"
    changed_when: false